### ISSUE TITLE
Y a quelqu'un?

### ISSUE THREAD

**Issue by LRimaz** [DigitalDW/proginter_projet_G3#4]
Personne ne me répond sur Waddsapp.

Il faut mieux travailler le CSS (et y a du boulot) et j'ai besoin de savoir si vous voyez des erreurs dans mon code.

**Comment by RPetkovic** [comment]
Y avait moi mais sans succès...

**Comment by RPetkovic** [comment]
Je vais essayer de faire les couleurs des statuts ce soir... Je vous tiens au courant
